### ISSUE TITLE
Support new field CKA_NSS_SERVER_DISTRUST_AFTER

### ISSUE THREAD

**Issue by tiran** [certifi/python-certifi#112]
The script ``mk-ca-bundle.pl`` generates a CA bundle from Mozilla NSS's certdata.txt. Recently Mozilla has introduced two new fields. The new fields ``CKA_NSS_SERVER_DISTRUST_AFTER`` and ``CKA_NSS_EMAIL_DISTRUST_AFTER`` encode a date after which the certificates are considered distrusted.

``mk-ca-bundle.pl`` should not add certs that have ``CKA_NSS_SERVER_DISTRUST_AFTER`` after the current date. The field is either a ``CK_BBOOL`` with value ``CK_FALSE`` or a ``MULTILINE_OCTAL`` that encodes the date as octal string "YYMMDDHHMMSSZ", e.g. ``\062\060\060\066\061\067\060\060\060\060\060\060\132`` == ``200617000000Z`` == 2020-06-17 00:00:00Z.

https://bugzilla.mozilla.org/show_bug.cgi?id=1465613

**Comment by Lukasa** [comment]
`mk-ca-bundle.pl` is not the source of truth for this repo, but `mkcert.org` is, and should be updated for this field.

**Comment by tiran** [comment]
I wrongly assumed that the the source of truth is powered by curl's ``mk-ca-bundle.pl`` and just copied my bug report https://github.com/curl/curl/issues/4834.

**Comment by Lukasa** [comment]
FYI it seems that "Entrust Root Certification Authority - G4" does not contain this field: https://hg.mozilla.org/mozilla-central/file/tip/security/nss/lib/ckfw/builtins/certdata.txt#l23359. I will be treating the absence of that field as the equivalent of `CK_BBOOL` with `CK_FALSE` until such time as there's guidance to do otherwise.

**Comment by Lukasa** [comment]
This is resolved with an update to mkcert.org.
