### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED inside docker

### ISSUE THREAD

**Issue by jkvargas** [certifi/python-certifi#194]
Hi, I am having the following issue when running some code that is using certifi in docker with an ubuntu image.
"requests.exceptions.SSLError: HTTPSConnectionPool(host=''myaddress", port=443): Max retries exceeded with url: /someUrl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))"

Now, the same code when executed locally with pycharm runs fine.
I am pointing SSL_CERT_FILE to /etc/ssl/certs/ca-certificates.crt and no luck.
Would you guys advise on what should I try?
Thanks.

**Comment by Lukasa** [comment]
SSL_CERT_FILE has no effect on certifi: we only read a single file. I recommend first checking with the requests team that your configuration is identical (especially around environment variables), and then I recommend checking whether your certifi versions are identical. Finally, it may be worth checking whether the requests folks have started using the system trust store on your local machine instead of certifi. Certifi at the same version number is identical on all platforms.
