### ISSUE TITLE
`pip freeze` has unexpected output (`@ file`) for `certifi>2022.5.18.1` in a `conda` environment

### ISSUE THREAD

**Issue by zacharyburnett** [certifi/python-certifi#205]
```shell
conda create -n test_certifi python
conda activate test_certifi
```
For any version of `certifi` after `2022.5.18.1`, running `pip freeze` results in output like the following:
```
pip install -U certifi
pip freeze
```
```requirements.txt
certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_0ek9yztvu3/croot/certifi_1665076692562/work/certifi
```
Running `pip freeze` on `certifi<=2022.5.18.1` has more expected output:
```shell
pip install -U certifi==2022.5.18.1
pip freeze
```
```requirements.txt
certifi==2022.5.18.1
```

**Comment by sigmavirus24** [comment]
We don't control pip's output and I doubt we changed anything relevant to this.

**Comment by sigmavirus24** [comment]
> Just to make sure, @sigmavirus24, how is that exactly relevant to the pip but not python-certifi?

Pip controls what the format of it's output is, not the package(s) it's outputting information about

**Comment by woosal1337** [comment]
Got it, very confusing of pip there.

**Comment by akshayaureatelabs** [comment]
@zacharyburnett Hello,
It's possible that the unexpected output you're seeing with pip freeze in your conda environment is related to a known issue with the certifi package version 2022.5.18.1.

This issue occurs because certifi version 2022.5.18.1 is not compatible with the version of OpenSSL that is installed in the conda environment. When pip freeze tries to list the installed packages, it encounters this incompatibility and outputs an error message.

To resolve this issue, you can try upgrading the openssl package in your conda environment to a version that is compatible with certifi version 2022.5.18.1. You can do this by running the following command in your conda environment:
`conda install openssl=1.1.1k`

This will install version 1.1.1k of the openssl package, which is compatible with certifi version 2022.5.18.1.

After upgrading openssl, you should be able to run pip freeze without encountering any unexpected output related to certifi.

**Comment by alex** [comment]
There doesn't seem to be any action for us to take here.
