### ISSUE TITLE
Trusted certs pulled over insecure channel

### ISSUE THREAD

**Issue by Prandium** [certifi/python-certifi#23]
Currently certifi is pulling the ca-bundle over a non-TLS protected channel (http), which means that anyone between the host and ci.kennethreitz.org can inject or completely modify the ca certificates bundle to inject their own trusted ca, allowing them to man-in-the-middle tls traffic between python clients and any site they connect to. 

To address this, the ca bundle should be hosted on a site protected by TLS, and https://github.com/certifi/python-certifi/blob/master/tasks.py#L5 should be updated to reflect the new endpoint.

**Comment by sigmavirus24** [comment]
https://ci.kennethreitz.org/job/ca-bundle/lastSuccessfulBuild/artifact/cacerts.pem is not available. Please advise @Prandium

**Comment by Lukasa** [comment]
It's ok folks! certifi has not been pulling certs from kennethreitz.org for a little while now, we get them from mkcert.org instead. mkcert is not available over HTTP at all, so we're safe in that regard.

You're right, however, that the tasks.py should be updated. I haven't updated it because I don't actually use it (`curl -o certs.pem https://mkcert.org/generate/` is not that hard a command to remember).

**Comment by Lukasa** [comment]
Resolved in 5ae6cbfa6848d74639e3a049f9dbcab2d219273f. Thanks @Prandium!
