### ISSUE TITLE
Failure to access google storage apis when using the requests module - SSL3_GET_SERVER_CERTIFICATE

### ISSUE THREAD

**Issue by odedfos** [certifi/python-certifi#32]
When the certifi package is installed together with the requests module the following domain certificate fails validation: https://storage.googleapis.com/

    Traceback (most recent call last):
      File "run.py", line 4, in <module>
        requests.get('https://storage.googleapis.com/')
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
        response = session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 471, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 579, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 430, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)

**Comment by Lukasa** [comment]
@odedfos Can you confirm whether or not this is the same problem as #26? That is, try passing `certifi.old_where()` to the `verify` argument of requests.

**Comment by odedfos** [comment]
yes, it seems to be the same issue, works with certifi.old_where()

Is there an estimation for a fix that will not require reinstalling a bunch of crypto packages?

**Comment by Lukasa** [comment]
@odedfos Yes: either use `certifi.old_where()` or upgrade your Linux distribution.

To be clear, there is *no* fix for this from Python-land other than using `certifi.old_where()` or upgrading OpenSSL. The OpenSSL on your system is too old to properly verify cross-signed TLS certificates, and three is no way for that problem to be resolved on my end. Your system is being put at *significant risk* if you use `certifi.old_where()` because you are continuing to base your trust on 1024-bit RSA certificates, which have been being deprecated since 2012 and are subject to several known attacks already.

I cannot stress this enough, you should *strongly* consider upgrading to a newer version of OpenSSL, either via building static wheels or by moving to a newer release of whatever Linux distribution you're using.
