### ISSUE TITLE
How does this compare to the debian package 'ca-certificates'?

### ISSUE THREAD

**Issue by JonasGroeger** [certifi/python-certifi#35]
For the CAs installed there: https://packages.debian.org/jessie/all/ca-certificates/filelist

Why should I use certifi?!

**Comment by Lukasa** [comment]
There are a few differences.

Firstly, Debian Jessie includes certificates that have been deprecated by the CA/Browser forum because their keys are weak (1024-bit). Those certificates are removed from certifi by default (though available on request). These are necessary because Jessie's OpenSSL is old.

Secondly, not all users are on Debian, and so their certificates may not always in the same place or be the same. Certifi ensures that you can always find them, and that they're always the same. The world is bigger than just Debian.

Thirdly, and most importantly, Debian *does not properly process the Mozilla certificate data bundle*. In particular, the Mozilla certificate data bundle marks some certificates as `CKT_NSS_MUST_VERIFY_TRUST` for the purposes of TLS. These certificates are **not trusted for use with securing TLS connections**, instead only safe for S/MIME or code signing. However, Debian does not persist that trust property through to their bundle correctly (as tracked in [this Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=721976) and originally reported in [this Ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/ca-certificates/+bug/1207004)). This means that using the Debian trust bundle leads you to incorrectly trust root certificates you should not be trusting.

Certifi *does* correctly process this field and ships a trust bundle that is suitable *only* for TLS.

**Comment by Lukasa** [comment]
Note also that the Debian bug has been open for *two years now*. They're clearly not that bothered about solving the problem in a timely fashion.

**Comment by ychaouche** [comment]
I might something stupid but what happens to all the servers that are certified with 1024-bit keys if you remove the CAs that signed their certificates ?

**Comment by Lukasa** [comment]
@ychaouche Servers should not have been issued certs with 1024-bit keys for a *long* time. They have been phased out by the CA/Browser forum since 2013 and all of them had to have been revoked and replaced with 2048-bit keys.
