### ISSUE TITLE
Using distutils

### ISSUE THREAD

**Issue by jakirkham** [certifi/python-certifi#42]
Seems this uses `setuptools`. However, it doesn't look like the nice features of `setuptools` are being used (unless I missing something). Is there any reason not to just use `distutils`?

**Comment by alex** [comment]
Is there any reason to prefer distutils? AFAIK setuptools is necessary to make wheels work.

**Comment by jakirkham** [comment]
So, if one wished to package `setuptools` with `certifi`, the circular dependency would be problematic.

**Comment by jakirkham** [comment]
Maybe a compromise would be a fallback to `distutils`. Does that seem acceptable?

**Comment by dstufft** [comment]
This is a bit complicated because setuptools can depend on certifi, and a system that wishes to express that dependency chain will end up with a circular dependency. A similar problem exists for the packaging library and we use the setuptools/distutils fallback to achieve this, see [pypa/package:setup.py](https://github.com/pypa/packaging/blob/c22fbd8c7bfa989df911243b10901645b7d4758d/setup.py#L10-L19).

If certifi cares about this use case, I suggest just stealing that block.

**Comment by jakirkham** [comment]
See PR ( https://github.com/certifi/python-certifi/pull/43 ), which does exactly that. Feedback welcome.
