### ISSUE TITLE
Google Internet Authority G2 and Equifax Secure Certificate Authority not included?

### ISSUE THREAD

**Issue by bastbnl** [certifi/python-certifi#47]
First of all I'd like you thank you for your efforts in working on a safer web. I do have a question on that safety though...

I'm using django-allauth and certifi since it's installed via dependencies. Django-allauth comes with a bunch of oauth "clients" and one them is Google. I learned that I'm not able to work with the Google OAuth flow when I'm using plain certifi as both **Google Internet Authority G2** and **Equifax Secure Certificate Authority** are not included in the bundle shipped with certifi.

I know (http://www.tenberge-ict.nl/solving-sslerror-at-accountsgooglelogincallback-on-django-allauth/)  what I did to get the software running, but I'm repeating this after each certifi update, which got me wondering. It looks like those CA's are not in the trust list. Why?

**Comment by Lukasa** [comment]
There are two different answers.

For Google's, it's not present because it's not a root CA: it's an intermediary CA. The list is primarily intended to contain only trust roots. The issuer of the Google Internet Authority G2 certificate *is* present in the trust bundle ("GeoTrust Global CA"), so as long as the site in question is sending their intermediate CA certificate (which they should be), it'll be trusted.

As to Equifax, the certificate in question is a 1024-bit root certificate. These are formally deprecated because they are weak and vulnerable to attack. For this reason, they are not in the trust store. However, because users frequently still need them, you can find it in `certifi.old_where()`. This is also related to #26.

**Comment by bastbnl** [comment]
Thanks for the update. I tried if I could get my issue resolved without the Google Internet Authority G2 certificate and it worked out. Guess I'll have to update that blog post

Is there any way to extend the trusted ca certificates bundle using some form of include? It would save me some work adding the Equifax certificate after each update. The certifi bundle is referenced in another module, which I'd prefer not to change

**Comment by Lukasa** [comment]
The only reason you'd need to add the Equifax bundle each time is if you cannot pass an alternative path or request the old bundle. If that's the case, then currently there is not any system for injecting certificates into the bundle globally, and I'd be pretty nervous about adding one.
