### ISSUE TITLE
The way certifi is updated seems hard to maintain in production and is possibly a security risk

### ISSUE THREAD

**Issue by yoni1** [certifi/python-certifi#48]
This is possibly a misunderstanding of mine, so please correct me if I'm wrong.

The CA bundle is updated in certifi simply by pushing a new version of certifi to github and pypi. This has a simple security consequence: Any Python code that uses certifi does not use the latest CA bundle until certifi is explicitly updated. Unlike traditional package updates, *all* (or almost all) certifi updates are by design security updates (and rarely feature updates), and these are pretty frequent: Once or twice a month. For other packages, security updates are pretty infrequent. Thus, security-conscious developers would want to update certifi with every new release.

Sometimes, this is not so simple. For instance, consider a Python web server that uses requests to make outside REST API calls and certifi to secure them. Such servers can be up for months or longer. Updating the certifi package would require the server (at least the Python part of it) to restart, which can be undesirable.

Another complication is caused by pip's `requirements.txt` format. Many Python hosts (for example, Heroku, or Amazon Elastic Beanstalk, or Google App Engine...) take a pip `requirements.txt` file along with your code and set up an environment using this file. The "recommended" way to create this file is to run `pip freeze`. Unfortunately, this command pins down the version of packages, so you could get something like `certifi==2016.8.8`, which is somewhat of a security risk - you would never get an up-to-date CA bundle.

Furthermore, even if you do change the `requirements.txt` line to something like `certifi` or `certifi>=2016.8.8`, if your environment is set up using `pip install -r requirements.txt` and it already had an old version of certifi installed, it would not get upgraded. It only gets upgraded if `pip install` explicitly gets the `-U` switch; there is no way to "force an upgrade" through the `requirements.txt` file alone.

I am not sure what the best way to remedy this would be, but I suggest decoupling the certifi version from the bundle version and having certifi try to auto-update the bundle every, say, 24 hours, from a reliable source like mkcert.org (using certificate pinning to enhance security and to avoid having a chicken and egg problem).

Thanks for a great package!

**Comment by Lukasa** [comment]
I am *extremely* reluctant to have certifi obtain its certificates "live". This is for a few reasons.

Firstly, a *surprising* number of developers would rather have their applications continue to function rather than shut down in the face of a security change. The fact that certifi so rapidly moves forward to keep up to speed with the changes Mozilla makes already leaves quite a few developers uncomfortable.

But secondly, and more importantly, it places higher demands on the infrastructure than I can currently effectively maintain. Right now `mkcert.org` is basically a best-effort maintenance job by me, and while I think I'm doing a pretty good job it doesn't change the fact that `mkcert.org` is currently not well-equipped to certificate pin. Ultimately, unless I had more time set aside to devote to building out infrastructure for `mkcert.org`, distributing certificates that way ultimately concerns me far more than distributing them via `pip`.

Ultimately, the current deployment model makes it pretty easy for application developers to say they always want the current certifi: remove any version pins for deployment, and then upgrade on some kind of regular interval. Moving to another form of distribution would certainly be possible, but I think would require more thinking about how to bootstrap the trust.

**Comment by yoni1** [comment]
Fair enough :)
