### ISSUE TITLE
Lets Encrypt Root CA missing

### ISSUE THREAD

**Issue by alexandrezia** [certifi/python-certifi#55]
Please add Lets Encrypt root CA:

https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt

Thanks

**Comment by Lukasa** [comment]
Thanks for the suggestion!

That is not how certifi works. Certifi is just directly the contents of Mozilla's cert database. Until and unless it is added there, it will not be added here. As it happens it's not enormously important, because LE's root cert is cross-signed by a root that *is* in our trust bundle, so LE certs validate just fine.
