### ISSUE TITLE
Missing CA

### ISSUE THREAD

**Issue by nikokio** [certifi/python-certifi#73]
Hello,

The following intermediate CA is unknown in Certifi :

C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 Secure Server CA - G4

It can be seen here : https://www.erlang.org/downloads

Thanks

**Comment by alex** [comment]
That certificate is an intermediate. certifi does not include intermediate certificates, it includes the root certificate there: "VeriSign Class 3 Public Primary Certification Authority - G5".

It looks like the server is misconfigured and does not send the intermediate certificate necessary to build the full chain. I'd report this to the server operators. (This will often work ok in browsers, because they cache intermediate, perform AIA chasing to find new intermediates, or both. Non-browser clients almost never implement this behaviour).
